// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{1}
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Passphrase    string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type PasswdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passphrase    string                 `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	NewPassphrase string                 `protobuf:"bytes,2,opt,name=new_passphrase,json=newPassphrase,proto3" json:"new_passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswdRequest) Reset() {
	*x = PasswdRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswdRequest) ProtoMessage() {}

func (x *PasswdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswdRequest.ProtoReflect.Descriptor instead.
func (*PasswdRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PasswdRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *PasswdRequest) GetNewPassphrase() string {
	if x != nil {
		return x.NewPassphrase
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_internal_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{5}
}

// Request wraps exactly one operation via oneof.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Get
	//	*Request_List
	//	*Request_Set
	//	*Request_Delete
	//	*Request_Passwd
	//	*Request_Stop
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Request) GetList() *ListRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Request) GetSet() *SetRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Request) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Request) GetPasswd() *PasswdRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Passwd); ok {
			return x.Passwd
		}
	}
	return nil
}

func (x *Request) GetStop() *StopRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Get struct {
	Get *GetRequest `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type Request_List struct {
	List *ListRequest `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type Request_Set struct {
	Set *SetRequest `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type Request_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Request_Passwd struct {
	Passwd *PasswdRequest `protobuf:"bytes,5,opt,name=passwd,proto3,oneof"`
}

type Request_Stop struct {
	Stop *StopRequest `protobuf:"bytes,6,opt,name=stop,proto3,oneof"`
}

func (*Request_Get) isRequest_Payload() {}

func (*Request_List) isRequest_Payload() {}

func (*Request_Set) isRequest_Payload() {}

func (*Request_Delete) isRequest_Payload() {}

func (*Request_Passwd) isRequest_Payload() {}

func (*Request_Stop) isRequest_Payload() {}

// Response is the same shape for all operations.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Response) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_agent_agent_proto protoreflect.FileDescriptor

const file_internal_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/agent/agent.proto\x12\x05agent\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\r\n" +
	"\vListRequest\"T\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\"A\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"V\n" +
	"\rPasswdRequest\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\x12%\n" +
	"\x0enew_passphrase\x18\x02 \x01(\tR\rnewPassphrase\"\r\n" +
	"\vStopRequest\"\x96\x02\n" +
	"\aRequest\x12%\n" +
	"\x03get\x18\x01 \x01(\v2\x11.agent.GetRequestH\x00R\x03get\x12(\n" +
	"\x04list\x18\x02 \x01(\v2\x12.agent.ListRequestH\x00R\x04list\x12%\n" +
	"\x03set\x18\x03 \x01(\v2\x11.agent.SetRequestH\x00R\x03set\x12.\n" +
	"\x06delete\x18\x04 \x01(\v2\x14.agent.DeleteRequestH\x00R\x06delete\x12.\n" +
	"\x06passwd\x18\x05 \x01(\v2\x14.agent.PasswdRequestH\x00R\x06passwd\x12(\n" +
	"\x04stop\x18\x06 \x01(\v2\x12.agent.StopRequestH\x00R\x04stopB\t\n" +
	"\apayload\"Z\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB,Z*github.com/brickpop/secrets/internal/agentb\x06proto3"

var (
	file_internal_agent_agent_proto_rawDescOnce sync.Once
	file_internal_agent_agent_proto_rawDescData []byte
)

func file_internal_agent_agent_proto_rawDescGZIP() []byte {
	file_internal_agent_agent_proto_rawDescOnce.Do(func() {
		file_internal_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_agent_proto_rawDesc), len(file_internal_agent_agent_proto_rawDesc)))
	})
	return file_internal_agent_agent_proto_rawDescData
}

var file_internal_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_agent_agent_proto_goTypes = []any{
	(*GetRequest)(nil),    // 0: agent.GetRequest
	(*ListRequest)(nil),   // 1: agent.ListRequest
	(*SetRequest)(nil),    // 2: agent.SetRequest
	(*DeleteRequest)(nil), // 3: agent.DeleteRequest
	(*PasswdRequest)(nil), // 4: agent.PasswdRequest
	(*StopRequest)(nil),   // 5: agent.StopRequest
	(*Request)(nil),       // 6: agent.Request
	(*Response)(nil),      // 7: agent.Response
}
var file_internal_agent_agent_proto_depIdxs = []int32{
	0, // 0: agent.Request.get:type_name -> agent.GetRequest
	1, // 1: agent.Request.list:type_name -> agent.ListRequest
	2, // 2: agent.Request.set:type_name -> agent.SetRequest
	3, // 3: agent.Request.delete:type_name -> agent.DeleteRequest
	4, // 4: agent.Request.passwd:type_name -> agent.PasswdRequest
	5, // 5: agent.Request.stop:type_name -> agent.StopRequest
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_agent_agent_proto_init() }
func file_internal_agent_agent_proto_init() {
	if File_internal_agent_agent_proto != nil {
		return
	}
	file_internal_agent_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*Request_Get)(nil),
		(*Request_List)(nil),
		(*Request_Set)(nil),
		(*Request_Delete)(nil),
		(*Request_Passwd)(nil),
		(*Request_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_agent_proto_rawDesc), len(file_internal_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_agent_agent_proto_goTypes,
		DependencyIndexes: file_internal_agent_agent_proto_depIdxs,
		MessageInfos:      file_internal_agent_agent_proto_msgTypes,
	}.Build()
	File_internal_agent_agent_proto = out.File
	file_internal_agent_agent_proto_goTypes = nil
	file_internal_agent_agent_proto_depIdxs = nil
}
